#:schema node_modules/wrangler/config-schema.json
name = "warp-vips"
main = "src/index.js"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
STORE_R2 = true
R2_FILENAME = "warp_vips.json"

[triggers]
crons = ["*/5 * * * *"] # run every 5 minutes

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "warp-vips"